/**
 * Hotspots
 */
export const ADD_HOTSPOT = 'ADD_HOTSPOT';
export type ADD_HOTSPOT = typeof ADD_HOTSPOT;

export const DELETE_HOTSPOT = 'DELETE_HOTSPOT';
export type DELETE_HOTSPOT = typeof DELETE_HOTSPOT;

export const MOVE_HOTSPOT_UP = 'MOVE_HOTSPOT_UP';
export type MOVE_HOTSPOT_UP = typeof MOVE_HOTSPOT_UP;

export const MOVE_HOTSPOT_DOWN = 'MOVE_HOTSPOT_DOWN';
export type MOVE_HOTSPOT_DOWN = typeof MOVE_HOTSPOT_DOWN;

/**
 * MyLocation
 */
export const FETCHING_COORDS = 'FETCHING_COORDS';
export type FETCHING_COORDS = typeof FETCHING_COORDS;

export const FAILED_FETCHING_COORDS = 'FAILED_FETCHING_COORDS';
export type FAILED_FETCHING_COORDS = typeof FAILED_FETCHING_COORDS;

export const SUCCEED_FETCHING_COORDS = 'SUCCEED_FETCHING_COORDS';
export type SUCCEED_FETCHING_COORDS = typeof SUCCEED_FETCHING_COORDS;

export const FETCHING_LOCATION = 'FETCHING_LOCATION';
export type FETCHING_LOCATION = typeof FETCHING_LOCATION;

export const FAILED_FETCHING_LOCATION = 'FAILED_FETCHING_LOCATION';
export type FAILED_FETCHING_LOCATION = typeof FAILED_FETCHING_LOCATION;

export const SUCCEED_FETCHING_LOCATION = 'SUCCEED_FETCHING_LOCATION';
export type SUCCEED_FETCHING_LOCATION = typeof SUCCEED_FETCHING_LOCATION;
